# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-04 07:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.datetime_safe


class Migration(migrations.Migration):

    dependencies = [
        ('webchecker', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parseddata',
            name='content',
        ),
        migrations.AddField(
            model_name='parseddata',
            name='date',
            field=models.CharField(default='2010-00-00', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parseddata',
            name='py_date',
            field=models.DateTimeField(default=django.utils.datetime_safe.datetime.now),
            preserve_default=False,
        ),
    ]
