# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-08 16:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webchecker', '0004_auto_20170109_0137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='using_options',
            field=models.ManyToManyField(blank=True, to='webchecker.Option'),
        ),
    ]
