# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-08 16:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webchecker', '0006_remove_guest_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='option',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
