# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-09 04:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webchecker', '0008_auto_20170109_0246'),
    ]

    operations = [
        migrations.CreateModel(
            name='CafeMenuInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('menu', models.TextField()),
                ('meal_time', models.CharField(choices=[('m', 'morning'), ('l', 'lunch'), ('d', 'dinner')], max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
