# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-09 04:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webchecker', '0009_cafemenuinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cafemenuinfo',
            name='meal_time',
            field=models.CharField(choices=[('morning', 'morning'), ('lunch', 'lunch'), ('dinner', 'dinner')], max_length=20),
        ),
    ]
