# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-09 04:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webchecker', '0010_auto_20170109_1315'),
    ]

    operations = [
        migrations.CreateModel(
            name='CafeMealTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meal', models.CharField(choices=[('morning', 'morning'), ('lunch', 'lunch'), ('dinner', 'dinner')], max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='cafemenuinfo',
            name='meal_time',
        ),
        migrations.AddField(
            model_name='guest',
            name='meal_time',
            field=models.ManyToManyField(blank=True, to='webchecker.CafeMealTime'),
        ),
    ]
