# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-09 04:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webchecker', '0011_auto_20170109_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cafemealtime',
            name='meal',
            field=models.CharField(choices=[('morning', 'morning'), ('lunch', 'lunch'), ('dinner', 'dinner')], max_length=20, unique=True),
        ),
    ]
